### ISSUE TITLE
Failed to load library: SDL2.dll WindowsDX

### ISSUE THREAD

**Issue by Mootfrost777** [kniEngine/kni#1417]
When I am trying to run a WindowsDX(multiplatform project), it throws this error.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by nkast** [comment]
WindowsDX doesn't use SDL.
Probably you are referencing the DesktopGL library from a library, that makes it into the final \bin\ folder.

See *[1] for an example on how to use the Ref nuget with a Library.
Remove the DesktopGL reference and add:
  `<PackageReference Include="nkast.Xna.Framework.Ref" Version="3.11.9002" PrivateAssets="All" />`
  
  Since v3.11, _Content_, _Graphics_, _Audio_ and _Media_ classes have been [decoupled](http://blog.nkast.gr/post/what-s-new-in-kni-v3-11). The core classes and _Design_ were are already [decoupled in v3.9](http://blog.nkast.gr/post/what-s-new-in-kni-v3-9-9001).
  You'd only need the Ref library for Input and Game classes. Soon those will be moved on their own libraries, and we will no longer need a PrivateAssets Ref library to bait&switch.

*[1] https://github.com/kniEngine/kni/blob/main/Documentation/articles/migrate_381.md

I've opened a couple of Categories in https://github.com/kniEngine/kni/discussions, 
so for now on you can post user-issues there.
I 'am closing this, since _Issue_ are for verified bugs and planed features only.
