### ISSUE TITLE
BlendState.NonPremultiplied gives very different results on WindowsDX versus BlazorGL

### ISSUE THREAD

**Issue by jordi-z80** [kniEngine/kni#1728]
KNI 3.12.9001 (nuget) , Window10 , BlazorGL 

The following code:

<code>

			spriteBatch.Begin ();
			spriteBatch.Draw (tex, new Vector2 (0, 0), Color.White);
			spriteBatch.End ();

			int alpha = 192;
			Color shadeColor = new Color (0, 0, 0, alpha);
			spriteBatch.Begin (blendState: BlendState.NonPremultiplied);
			spriteBatch.Draw (whiteTex, new Rectangle (0, 0, 384, 384), shadeColor);
			spriteBatch.End ();
</code>

gives very different results on WindowsDX versus BlazorGL. 

on WindowsDX:
![image](https://github.com/user-attachments/assets/a5795bfd-5371-4403-98ec-5b5ff6ce6f6b)

on BlazorGL
![image](https://github.com/user-attachments/assets/d3d40df2-04f2-477f-bddc-1d31d95382b8)

Sample test:

https://github.com/jordi-z80/FadeoutTest1

Thanks!

**Comment by nkast** [comment]
That seems to be the issues where the Canvas is blended with the page background.
https://webglfundamentals.org/webgl/lessons/webgl-and-alpha.html

The template was updated to make the canvas holder black in order to get similar results with desktop. 
You can apply the same change in your project manually in Index.Razor 
https://github.com/kniEngine/kni/pull/1695/files

**Comment by jordi-z80** [comment]
Thanks, it worked! :)
