### ISSUE TITLE
Left and Right Triggers on Gamepad don't seem to work

### ISSUE THREAD

**Issue by andrewandrepowell** [kniEngine/kni#1761]
The Left and Right Triggers don't seem to work in the latest version of KNI. 

Here's a link to my reference project that demonstrates the issue:

https://github.com/andrewandrepowell/KniControllerExample

#### What version of KNI does the bug occur on:
- KNI 3.13.9001

#### What operating system are you using:
- Windows10

#### What KNI platform are you using:

- BlazorGL

**Comment by andrewandrepowell** [comment]
Did some more digging and found out it appears to be the function I'm calling. The following fails:

https://github.com/andrewandrepowell/KniControllerExample/blob/98d0997c93d8827fb631c55fcab59387024133bb/KniControllerExampleGame.cs#L91

But the following works:

https://github.com/andrewandrepowell/KniControllerExample/blob/98d0997c93d8827fb631c55fcab59387024133bb/KniControllerExampleGame.cs#L118

But if I get the value from `state.Triggers.Right`, it changes as I expected.

**Comment by nkast** [comment]
I can't access the KniControllerExample repo.

I assume the problem is that you were accessing the LeftTrigger/RightTrigger virtual buttons, instead on GamepadState.Triggers

I left the code commented out, because at the moment I wasn't sure if it's the right thing to do. 
I wanted to review how those buttons are handled on other platforms.

https://github.com/kniEngine/kni/blob/main/Platforms/Input/.Blazor/ConcreteGamePad.cs#L145-L148

**Comment by andrewandrepowell** [comment]
> I can't access the KniControllerExample repo.

Oops. Accidentally left it private. It's public now.

**Comment by andrewandrepowell** [comment]
> I assume the problem is that you were accessing the LeftTrigger/RightTrigger virtual buttons, instead on GamepadState.Triggers
>
> I left the code commented out, because at the moment I wasn't sure if it's the right thing to do.
> I wanted to review how those buttons are handled on other platforms.

(Apologize for the double post)

Hmmm. MonoGame.Framework.DesktopGL 3.8.1.303 does in fact implement those virtual buttons since that's what I've been using in my current game.
