### ISSUE TITLE
No touch events in BlazorGL project

### ISSUE THREAD

**Issue by dtaylorus** [kniEngine/kni#1820]
My BlazorGL project receives mouse input but receives no touch events and is therefore unusable on an iPhone.

I'll investigate further today to provide more specifics.

#### What version of KNI does the bug occur on:
- KNI 3.13.9001

#### What operating system are you using:
- Windows 11/Chrome, iOS 17.6.1/Safari

#### What KNI platform are you using:

- BlazorGL

**Comment by dtaylorus** [comment]
The condition

```
if ('ontouchstart' in window)
```

in Window.8.0.1.js returns false so the touch events aren't registered.

**Comment by dtaylorus** [comment]
I tried registering the events on both the window and the document with no success. They may need to move to the canvas.

**Comment by dtaylorus** [comment]
`window.addEventListener('touchstart', ...` is working where `window.ontouchstart = ...` is not.

**Comment by dtaylorus** [comment]
Next up `TouchPanelStrategy.DisplayWidth/Height` in `TouchPanelStrategy.Legacy.cs` are both 0 in the `AddPressedEvent` method so `TouchLocationData._position` is always (0, 0).

**Comment by dtaylorus** [comment]
I submitted a pull request for fixing the touch events on Chrome at https://github.com/nkast/Wasm/pull/6.

There's still a fix required for the TouchPanel DisplayWidth/Height TBD, and there appears to be an issue with the fake touch event id's that is invoking a lot of debug assertions.

**Comment by nkast** [comment]
The best place to set it is at the end on OnApplyChanges() overload,
right after PresentationParameters are set for backbafferWidth/height.
https://github.com/kniEngine/kni/blob/a22df9536ad7a6028d5e5929bd795e2658915755/Platforms/.Blazor/ConcreteGraphicsDeviceManager.cs#L80

Android set it at GameWindow.ClientBoundsChanged(...). It works, but it's not quite right.

The other platforms set an event on DeviceReset, but that is not yet implemented. And they never supported touch anyway.
There is no reason to dispatch an event internally, we can simply set the values right after the backbuffer dimessions are set, at the end of ApplyChanges().

**Comment by dtaylorus** [comment]
Thanks. That's one of the places I have it now. I'll remove the other places I have it and test it tomorrow and send you a pull request.

**Comment by nkast** [comment]
Maybe we also have to update it on window resize, I have to check.

**Comment by nkast** [comment]
Here are some more details, 

GraphicsDevice during initialization will override the PresentationParameters.BackBufferWidth/Height.
Because we don't have the power to resize the browser window, the PresentationParameters passed down from GraphicsDeviceManager are ignored.
https://github.com/kniEngine/kni/blob/main/Platforms/Graphics/.BlazorGL/ConcreteGraphicsDevice.cs#L61-L66

The GameWindow calls ApplyChanges() when browser is resized, to update the GraphicsDevice.PresentationParameters.
https://github.com/kniEngine/kni/blob/main/Platforms/Platform/Blazor/BlazorGameWindow.cs#L274-L277

So I think the best place to place a call to UpdateTouchPanel(...) is somewhere after the device is created, 
after a call to CreateDevice(gdi);
https://github.com/dtaylorus/MonoGame/blob/f3f759b4de6e5f28c8cc2a4e73110a7470cf2946/MonoGame.Framework/GraphicsDeviceManager.cs#L116
or inside that method at the end.

Also a call is needed at the end of ApplyChanges(), after the call to GraphicsDevice.Reset(gdi.PresentationParameters);
https://github.com/dtaylorus/MonoGame/blob/f3f759b4de6e5f28c8cc2a4e73110a7470cf2946/MonoGame.Framework/GraphicsDeviceManager.cs#L360

Also the input must always come from GraphicsDevice.PresentationParameters, because that's holding the actual backbuffer /window size.

The fix in TouchPanelStrategy is correct, I broke that when refactoring the TouchPanel.

**Comment by nkast** [comment]
I see that the Reset event is actually wired.
This is an issue with initialization. On Chrome emulator touch work after refresing the page, and resizing.
So perhaps we only need to set the TouchPanel in CreateDevice().
The integer division just works because it's always 1.

Meanwhile, I will investigate why the events aren't registering on the window from the start.

**Comment by dtaylorus** [comment]
The events not registering on the window are fixed by https://github.com/nkast/Wasm/pull/6

**Comment by nkast** [comment]
I found what is going on. Desktop browsers don't have touch support. It's only when I open Dev-tools and enable the mobile device emulator that touch events are presents, that's why I needed to refresh the page. 

That also address part of your issues. You mention that events are not registered on Windows 11/Chrome. 
That is by design. If you have a touch screen, any events will be emulated as mouse events.
That is also what will happen in mobile that doesn't support touch. The events will appear as Mouse events.
 
 If fix the issue with the initialization of TouchPanel, by placing it right after the GraphicsDevice creation #1837.
 I've tested it on an android device and it's working. The update method on the DeviceReset is firing just as excepted. I remembered why I put it there. Reset() can also be called by the user, not just from inside ApplyChanges().

**Comment by nkast** [comment]
I am going to review your wasm change next. 
Do you have any theory why those changes are needed in iOS?

According to the documentation, any event should be available via a property, or AddEventListener, and the property is the only way to check if the feature exists. So, is this a bug in safari, or a known behavior?

**Comment by dtaylorus** [comment]
Touch events work great in Chrome on Windows 11 with my fix in your Wasm project dependency nkast/wasm#6. No need for developer mode.

If you have a touchscreen laptop browse to https://whamblegame.co<https://whamblegame.com>m/beta to try it for yourself. (There are a bunch of platform specific things I still need to port, but the basic functionality is there including touch in the browser.)
________________________________

**Comment by dtaylorus** [comment]
> I am going to review your wasm change next. 
> 
> Do you have any theory why those changes are needed in iOS?
> 
> 
> 
> According to the documentation, any event should be available via a property, or AddEventListener, and the property is the only way to check if the feature exists. So, is this a bug in safari, or a known behavior?  

I read that Chrome simply doesn't expose those touch events in the DOM as properties even though they exist via AddEventListener. It's not just on iOS. They're needed on Chrome for Windows as well. Apparently it's a well-known issue with Chrome.

**Comment by nkast** [comment]
I just went to the game you linked. Using Windows 10/Laptop with touchscreen. 

You are right, it does work! Both firefox and Chrome.
On dev console I can see that window.ontouchstart is not defined, 
but window.navigator.maxTouchPoints returns 10. 
So confusing. 

The [mozilla page](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#browser_compatibility) on touch, says that '_Touch events are typically available on devices with a touch screen, but many browsers make the touch events API unavailable on all desktop devices, even those with touch screens._'.

I misread that as, Touch functionality is not available on Desktop, while they meant that the event properties are not available.

I was testing your changes on an Android, everything fine there, nothing is broken. 
Also, on chrome, I can switch between the emulator back and forth, without refreshing the page. 
Which definitely is an improvement.

**Comment by dtaylorus** [comment]
Awesome. Thanks for getting to the bottom of this. Great to have a fully functional port of a MonoGame project on the web!
