### ISSUE TITLE
KNI 3.14 DesktopGL no longer works when referencing Framework.Ref

### ISSUE THREAD

**Issue by Epicguru** [kniEngine/kni#1900]
There seems to be an issue with the synchronization between DesktopGL and Framework.Ref.
Minimal project setup:
 - Game project, using `MonoGame.Framework.DesktopGL.9000` version `3.14.9001`. Game project also references library project below.
 - Library project, using `nkast.Xna.Framework.Ref` version `3.14.9001`.

**Expectation:** it should work and run as in previous version.
**Result:** `PlatformNotSupportedException` when creating GraphicsDeviceManager.
![image](https://github.com/user-attachments/assets/45608598-aee5-43b1-96e7-897c02025b7f)

This issue does not occur if I downgrade to DesktopGL.9000 version `3.13.9001` and Ref version `3.12.9001`.

#### What version of KNI does the bug occur on:
- KNI 3.14.9001

#### What operating system are you using:
- Windows11

#### What KNI platform are you using:
- DesktopGL

**Comment by nkast** [comment]
If you hit a PlatformNotSupported in the [constructor of GraphicsDeviceManager](  https://github.com/kniEngine/kni/blob/150f02b64ea10406f970326594afedfff2892e5b/Platforms/Game/.Ref/ConcreteGraphicsDeviceManager.cs#L14), it's because the Ref dll found its way to the final Bin folder.

The good news is that bait-and-switch belongs to the past. 
Gradually .Ref has been reduced to nothing...

You can remove the .Ref package from the library project.

**Comment by Epicguru** [comment]
Does this mean I should just be using .Framework in my library projects?

**Comment by nkast** [comment]
Yes! Only the core packages are needed for libraries.

The platform packages are
needed only on the main executable project.

**Comment by nkast** [comment]
I need to mark the .Ref package as obsolete. I dont think there is any benefit to upload any future version. 
The .Ref project now serves only as a template for future backends.

**Comment by Epicguru** [comment]
Understood, thanks for you help.
This is resolved then.
